name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # # Log in to GitHub Container Registry
    # - name: Log in to GitHub Container Registry
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/my-node-app:latest  --file Dockerfile .

    # Push the Docker image to GHCR
    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/my-node-app:latest


    
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag helloworld:latest
    # - name: Push Docker image to GHCR
    #   run: docker push helloworld:latest
